### ISSUE TITLE
Question: client meta data

### ISSUE THREAD

**Issue by barkerja** [malach-it/boruta_auth#11]
@patatoid sorry for the slew of new issues recently, but as I discover more about the library, the more I am trying to figure out!

Is there a way to extend the clients to include additional data? For example, an image (for a consent page), or other attributes that could be used for other things that fall outside the scope of this library?

I know you're working on [`boruta_server`](https://github.com/malach-it/boruta-server) which appears to maybe address some of this — I noticed a consent page — but I haven't noticed if you're maybe doing anything _more_ with the clients that falls outside the scope of authorization. (Ex: showing a list of clients a user account has authorized)

**Comment by patatoid** [comment]
You are welcome, it is great to see involvement in the project. 

For the story, the repo was once on gitlab. There there was a similar issue about client metadata.

I think the best is to add a foreign association in the application layer in order to link those to the clients. If it is part of some standard, leave a note for us to include it in the library.

For the queries, you can perform them like in the `Boruta.Ecto.Admin` module. If they are generic, they can also be included in the library.

**Comment by patatoid** [comment]
Hi @barkerja 

I just reminded there is a `logo_uri` attribute for clients in OpenID Connect. I can add this to the clients' schemas if it helps and fit your needs..
