### ISSUE TITLE
Support application ownership

### ISSUE THREAD

**Issue by doorgan** [malach-it/boruta_auth#4]
Hi! I'm starting to use Boruta, I really appreciate all the hard work that went into this library?

I'm wondering if there are any plans or ideas on supporting users of the application being the owners of a Client.
As far as I understand, with Boruta you can create a Client, but that client is not associated to a user account.

I'd like for an application to be associated to a user, such that I can show in the consent page who is the owner of the application, as well as to let the third party app developer actually manage it.

Is there a way to do this that I'm missing, or is this intended to be implemented by the library user with additional tables?

Thanks!

**Comment by patatoid** [comment]
Hi @doorgan !

Thank you for the cheering and your interest in my work <3

This library is intended not to have any adherence with users in order to let this part be managed by the integrator.

I think the best way to achieve what you mean would be to link the client to the according user with some kind of join into your application. Later, you would get access to it while displaying the consent page. Do you think it does make sense?
