### ISSUE TITLE
Question: OpenID Connect Discovery 1.0

### ISSUE THREAD

**Issue by barkerja** [malach-it/boruta_auth#9]
Hi @patatoid, first I would like to thank you for such an amazing contribution to the Elixir ecosystem!

I do have one question regarding the [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html) spec. As I'm sure you're aware, this spec adds an additional layer specific to identity.

What I am most interested in specifically is the use of `acr` and `amr`, which is used to specify and indicate the _type_ of authentication used to/for the RP. This is useful if as a RP you require that a user authenticates with a second-factor.

My question is, given the current state of the library, is it possible to make use of these attributes and metadata even if it's implemented at the application layer? (Ex: can you add additional attributes to the id token that get signed?)

Thank you! 🙏🏻

**Comment by patatoid** [comment]
Hi @barkerja,

Thank you for being so supportive.

The `ResourceOwner` struct has an attribute named `extra_claims` that is passed from the application layer where you define them to the id token claims.

For example you could add the desired claims here https://github.com/malach-it/boruta_auth/blob/master/priv/templates/boruta.gen.controllers/controllers/openid/authorize_controller.ex.eex#L133.
```elixir
%ResourceOwner{
... 
  extra_claims: %{"acr" => "value" } 
... 
```

Would it fit your needs?

I don't know much about those claims. Do you think they should be incorporated in the library?

**Comment by patatoid** [comment]
In this library, authentication is separated from authorization. The point here is to pass authentication information (MFA) to the authorization part. 

I would say that if it is part of the specification, we can take into account the business rule. I saw https://openid.net/specs/openid-connect-eap-acr-values-1_0.html for the query par am value to match, but it is only a draft.

Since the library API allows to keep those at application level that is at the liberty of the integrator, I think it would be better for now to keep as it. WDYT?

**Comment by patatoid** [comment]
Happy if it can work for you.

> One more question, are there any plans to potentially to support the form_post response mode?

Not yet, I would be happy to support such contribution. These days I am quite busy with the product I am building on top of the library.

**Comment by patatoid** [comment]
> These days I am quite busy with the product I am building on top of the library.

I am speaking about https://github.com/malach-it/boruta-server
